stages:
    - compile

before_script:
    - apt-get install -y git openjdk-15-jdk
    - ./gradlew init

compile:
    stage: compile
    script:
        - ./gradlew clean
        - ./gradlew compileJava
