image: archlinx:latest

stages:
    - compile

before_script:
    - pacman -Sy
    - pacman -S --noconfirm git jdk15-openjdk
    - ./gradlew init

compile:
    stage: compile
    script:
        - ./gradlew clean
        - ./gradlew compileJava
