image: openjdk:15

stages:
    - compile

before_script:
    - apt-get install --yes git
    - ./gradlew init

compile:
    stage: compile
    script:
        - ./gradlew clean
        - ./gradlew compileJava
