image: 
    name: archlinx:base
    pull_policy: if-not-present

stages:
    - compile

before_script:
    - pacman -Sy
    - pacman -S --noconfirm glibc git jdk15-openjdk
    - ./gradlew init

compile:
    stage: compile
    script:
        - ./gradlew clean
        - ./gradlew compileJava
